21 language translation
Hollo-Event-Notifier/Hollo-Event-Notifier-App pull request #67
Opened 2023-05-21 12:25 UTC by AndrasFerenczy

Should be kept in mind:

- @vbkristof has new design concepts regarding the toolbar (admin-root), this version is implemented in the design concepts of @AndrasFerenczy.
- Event's name are not translated, since this needs to be discussed how to be realised.
- The event's date (event-dialog-component) are also not translated.
- It should be discussed whether the admins can change languages differently (in the toolbar, not in the event-display-component as by normal users - my implementation follows this rule)

2023-05-21 12:58 UTC, vbkristof requested changes
Wow nagyon szép munka @AndrasFerenczy, büszke lehetsz rá. Van pár dolog amit majd kérlek még változtass meg, de az egész nagyon rendben van :smile:

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/core/services/translation.service.ts
> +  private translocoService : TranslocoService) {
ez lehetne `readonly`

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/core/transloco-root.module.ts
> +}
Ezt kiszedném egy külön service file-ba.

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/app.module.ts
> +  HttpClientModule
Ezeket a core-ba kéne tenni.

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/admin/admin.module.ts
> +  TranslocoModule
Ezt nézd meg, hogy lehet-e singleton. Ha igen akkor core-ba, ha nem akkor shared-be tedd kérlek.

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/admin/components/admin-root/admin-root.component.html
> +<div *transloco="let t; read:'admin-root'">
Ide egy `ng-container` is elég lenne, mert ennek a div-nek semmi szerepe nincs a renderelt DOM-ban.

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/admin/components/admin-root/admin-root.component.html
> +        <label for="settingsIcon">{{t('settings')}}</label>
Itt hogyhogy nem `mat-label`-t használsz?

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/admin/components/admin-root/admin-root.component.ts
> +  constructor(    private readonly translationService : TranslationService) {
fölösleges whitespace-k!

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/event-display/components/event-display-dialog/event-display-dialog.component.ts
> +  imports: [SharedModule, TranslocoModule]
Ugyanaz mint korábban, ha singleton tedd core-ba ha nem akkor shared-be.

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/event-display/event-display.component.ts
> +    private translationService: TranslationService,
`readonly`

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/login/login.component.ts
> +  imports: [SharedModule, TranslocoModule],
Itt is gond amit korábban írtam, core-ba vagy shared-be.

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/login/login.component.ts
> +    private translationService: TranslationService) {
`readonly`

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/features/login/login.component.ts
> +  protected readonly state = state;
Ez miért van itt?

2023-05-21 12:58 UTC, vbkristof commented on frontend/src/app/shared/components/full-calendar-wrapper/full-calendar-wrapper.component.ts
> +  private languageSubscription: Subscription | undefined;
kicsit elegánsabb írásmód ugyanerre: `private languageSubscription!: Subscription`

2023-05-21 12:59 UTC, vbkristof commented
Elindítottam és egy dolog még itt meglepett. Ez direkt van, hogy itt nem látszik a nyelv?
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/122607148/b2106b93-86bd-4fa0-99a5-de0d8138590c)

2023-05-22 08:52 UTC, AndrasFerenczy commented on frontend/src/app/core/transloco-root.module.ts
> +}
generált kód

2023-05-22 09:03 UTC, AndrasFerenczy commented on frontend/src/app/features/admin/components/admin-root/admin-root.component.html
> +        <label for="settingsIcon">{{t('settings')}}</label>
átirva

2023-05-22 09:23 UTC, AndrasFerenczy commented on frontend/src/app/features/login/login.component.ts
> +  protected readonly state = state;
törölve

2023-05-22 09:30 UTC, vbkristof approved these changes
gg wp please merge

2023-05-22 09:32 UTC, merged