51 upload report to code analizer tool
Hollo-Event-Notifier/Hollo-Event-Notifier-App pull request #72
Opened 2023-05-23 19:39 UTC by PeterH001

Mikor lefutottak a Github Actions feladatok feltűnt, hogy a Sonarcloudban nem jelennek meg a frontend fileok.
Ezért kitöröltem azt a feladatot, amely a backendet tölti fel, így aztán megjelent MINDEN file sonacloudban, a fronted és a backend egyaránt és mindent analizált. Szóval kitöröltem azt a jobot, így egy maradt, amire eredetileg azt gondoltam, hogy a frontendet fogja csupán feltölteni. 

Csatolok ide screenshotokat először arról, hogy mit láttam Sonarcloudban, amikor mind a kettő feladat lefutott és mit akkor, amikor csak az egyik (az analize frontend, amit végül bennehagytam):
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/1a3d20b8-bb08-424b-b7f2-7260217f72a2)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/9111b1bc-8000-43d7-a115-32794849459a)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/9509f085-c811-45d0-8adf-7534228160f0)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/2d370c06-acf2-4769-80b6-db7830346151)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/3ee1bdbc-05e6-40a7-9713-bb196f81d638)

--------------------------------

![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/cc655fa0-d59e-404d-a584-834c1271c99b)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/65fbba04-a343-470a-91b8-0ab14c238e05)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/39a116c4-9337-4ee0-bb14-3cecec3778c3)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/75c34c31-85b5-4f37-b41a-3c340609bf5d)
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/79469445/172ff3c5-2784-42d0-b9b2-557b63c138da)

2023-05-24 09:05 UTC, AndrasFerenczy commented
Szerintem jó lesz akkor úgy, hogy mindkettőt (backendet és frontendet) nézi.
@vbkristof mit gondolsz?

2023-05-24 14:26 UTC, vbkristof commented
> Szerintem jó lesz akkor úgy, hogy mindkettőt (backendet és frontendet) nézi. @vbkristof mit gondolsz?

Ha a kérdés arra vonatkozik hogy a sonarcloud feltöltés egyszerre egy jobban csinálja az FE-t és a BE-t is akkor szerintem jó lesz.

2023-05-24 14:28 UTC, vbkristof requested changes

2023-05-24 14:28 UTC, vbkristof commented on .github/workflows/validation.yml
> +  push:
Ez itt viszont nem az igazi

2023-05-24 14:28 UTC, vbkristof commented on backend/build.gradle.kts
> +
Whitespace változtatásokat ne mergeljunk lecci

2023-05-24 14:28 UTC, vbkristof commented on sonar-project.properties
> +# This is the name and version displayed in the SonarCloud UI.
Commentelt dolgokat kérlek szedd ki

2023-05-24 20:09 UTC, PeterH001 commented on sonar-project.properties
> +# This is the name and version displayed in the SonarCloud UI.
kiszedem én, de ez miért akkora probléma?

2023-05-24 20:12 UTC, vbkristof commented on sonar-project.properties
> +# This is the name and version displayed in the SonarCloud UI.
![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/122607148/4b2462ad-ee66-4e67-b5dc-e33f75eee2c0)

2023-05-24 20:18 UTC, PeterH001 commented
@vbkristof elvileg mostmár jónak kell lennie

2023-05-24 20:20 UTC, vbkristof commented
> @vbkristof elvileg mostmár jónak kell lennie

Szép lett, ilyenkor pro tipp, komment nélkül is rámbökhetsz :smile:

![image](https://github.com/Hollo-Event-Notifier/Hollo-Event-Notifier-App/assets/122607148/ca27b541-e681-40ce-95b0-8232e93be83e)

2023-05-24 20:20 UTC, vbkristof approved these changes
szép munka ha @AndrasFerenczy-nek is megfelel mehet a merge ;)

2023-05-27 09:03 UTC, AndrasFerenczy approved these changes
Good to go

2023-05-27 09:52 UTC, merged