35 event fetching
Hollo-Event-Notifier/Hollo-Event-Notifier-App pull request #88
Opened 2023-05-30 11:50 UTC by AndrasFerenczy

2023-05-30 13:35 UTC, vbkristof requested changes
Két apró dolog, de amúgy fullos :smile:

2023-05-30 13:35 UTC, vbkristof commented on frontend/src/app/features/admin/components/admin-event-display/admin-event-display.component.ts
>    }
Ha üres nyugodtan kiveheted a függvényt ;)

2023-05-30 13:35 UTC, vbkristof commented on frontend/src/app/shared/components/full-calendar-wrapper/full-calendar-wrapper.component.ts
> +    this.getEventsForCurrentView(datesSetArgs)
Ha csak itt van meghívva ez a fügvény nyugodtan ki lehet törölni és a tartalmát berakhatod a handleDateSet-be. Így könnyebb lesz tesztelni.

2023-05-31 07:52 UTC, AndrasFerenczy commented
Örülök, hogy tetszik ;)
módositottam amiket kértél.

2023-05-31 09:04 UTC, vbkristof approved these changes
Good job, mehet a merge

2023-05-31 10:44 UTC, merged